// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function mapMaybe(f, maybe) {
  return Belt_Option.map(maybe, f);
}

exports.mapMaybe = mapMaybe;
/* No side effect */
