// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


var GetWidgetProcess = 0;

var LoginProcess = 0;

var FakePrivilegeChecker = 0;

var AuthSvc = 0;

var WidgetSvc = 0;

var Cli = 0;

var CliLib = 0;

var CliUtil = 0;

var CmdShow = 0;

var FakeFsm = 0;

var CmdLogin = 0;

var FakeDeps = 0;

var Readline = 0;

var CmdAddWidget = 0;

var Db = 0;

var Data = 0;

var DbTypes = 0;

var Util = 0;

var Main = 0;

var Steps = 0;

var States = 0;

var MyProcess = 0;

var Fold = 0;

var Infix = 0;

var Domain = 0;

var Engine = 0;

var Parser = 0;

var StrMap = 0;

var AstDump = 0;

var Codegen = 0;

var DefMapper = 0;

var FloFuture = 0;

var DomainDefaults = 0;

var ParserExpt = 0;

var ParserTest = 0;

var SampleDefs = 0;

var AllDefaultsTest = 0;

var Machine = 0;

var FsmGeneric = 0;

var TransactionFsm = 0;

var Types = 0;

var SvcTypes = 0;

var AuthTypes = 0;

var WidgetTypes = 0;

var ProcessTypes = 0;

var PrivilegeTypes = 0;

exports.GetWidgetProcess = GetWidgetProcess;
exports.LoginProcess = LoginProcess;
exports.FakePrivilegeChecker = FakePrivilegeChecker;
exports.AuthSvc = AuthSvc;
exports.WidgetSvc = WidgetSvc;
exports.Cli = Cli;
exports.CliLib = CliLib;
exports.CliUtil = CliUtil;
exports.CmdShow = CmdShow;
exports.FakeFsm = FakeFsm;
exports.CmdLogin = CmdLogin;
exports.FakeDeps = FakeDeps;
exports.Readline = Readline;
exports.CmdAddWidget = CmdAddWidget;
exports.Db = Db;
exports.Data = Data;
exports.DbTypes = DbTypes;
exports.Util = Util;
exports.Main = Main;
exports.Steps = Steps;
exports.States = States;
exports.MyProcess = MyProcess;
exports.Fold = Fold;
exports.Infix = Infix;
exports.Domain = Domain;
exports.Engine = Engine;
exports.Parser = Parser;
exports.StrMap = StrMap;
exports.AstDump = AstDump;
exports.Codegen = Codegen;
exports.DefMapper = DefMapper;
exports.FloFuture = FloFuture;
exports.DomainDefaults = DomainDefaults;
exports.ParserExpt = ParserExpt;
exports.ParserTest = ParserTest;
exports.SampleDefs = SampleDefs;
exports.AllDefaultsTest = AllDefaultsTest;
exports.Machine = Machine;
exports.FsmGeneric = FsmGeneric;
exports.TransactionFsm = TransactionFsm;
exports.Types = Types;
exports.SvcTypes = SvcTypes;
exports.AuthTypes = AuthTypes;
exports.WidgetTypes = WidgetTypes;
exports.ProcessTypes = ProcessTypes;
exports.PrivilegeTypes = PrivilegeTypes;
/* No side effect */
