// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");
var CliLib$Iconixfw = require("./CliLib.bs.js");

var options = {
  input: (process.stdin),
  output: (process.stdout)
};

var readline = Readline.createInterface(options);

function cli(param) {
  var param$1 = function (line) {
    CliLib$Iconixfw.processLine(line);
    return cli(/* () */0);
  };
  readline.question("cli> ", param$1);
  return /* () */0;
}

cli(/* () */0);

exports.cli = cli;
/* options Not a pure module */
