// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");
var CliLib$Iconixfw = require("./CliLib.bs.js");

var options = {
  input: (process.stdin),
  output: (process.stdout)
};

var readline = Readline.createInterface(options);

function read(param) {
  readline.question("cli> ", param);
  return /* () */0;
}

function cli(param) {
  return read((function (line) {
                CliLib$Iconixfw.processLine(line);
                return cli(/* () */0);
              }));
}

cli(/* () */0);

exports.options = options;
exports.readline = readline;
exports.read = read;
exports.cli = cli;
/* options Not a pure module */
