// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Types$Iconixfw = require("../types/Types.bs.js");
var CliUtil$Iconixfw = require("./CliUtil.bs.js");
var WidgetSvc$Iconixfw = require("../svclayer/WidgetSvc.bs.js");

function run(request) {
  return Types$Iconixfw.ffold(CliUtil$Iconixfw.extractErr, CliUtil$Iconixfw.extractResult, WidgetSvc$Iconixfw.addWidget(request));
}

exports.run = run;
/* Types-Iconixfw Not a pure module */
