// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Types$Iconixfw = require("../types/Types.bs.js");
var AuthSvc$Iconixfw = require("../svclayer/AuthSvc.bs.js");
var CliUtil$Iconixfw = require("./CliUtil.bs.js");
var FakeDeps$Iconixfw = require("./FakeDeps.bs.js");

function login(username, pass) {
  return AuthSvc$Iconixfw.login(FakeDeps$Iconixfw.LoginDeps[/* get */0](/* () */0), username, pass);
}

function run(username, pass) {
  return Types$Iconixfw.ffold(CliUtil$Iconixfw.extractErr, CliUtil$Iconixfw.extractResult, login(username, pass));
}

exports.run = run;
/* Types-Iconixfw Not a pure module */
