// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Db$Iconixfw = require("../dblayer/Fake/Db.bs.js");
var Infix$Iconixfw = require("../framework/parser/Infix.bs.js");
var Types$Iconixfw = require("../types/Types.bs.js");
var FakeFsm$Iconixfw = require("./FakeFsm.bs.js");
var TransactionFsm$Iconixfw = require("../framework/Fsm/TransactionFsm.bs.js");

var runFsm = FakeFsm$Iconixfw.FakeTransactionFsm[/* run */1];

function worker(ctx) {
  var match = ctx[/* data */2];
  if (match.tag) {
    return Types$Iconixfw.freject("invalid input to login worker");
  } else {
    return Infix$Iconixfw.$less$$great(Db$Iconixfw.FakeDb[/* findWidget */3](match[0][/* id */0]), (function (param) {
                  return TransactionFsm$Iconixfw.updateWorkerData(ctx, /* Result */Block.__(1, [param]));
                }));
  }
}

function buildReq(req) {
  return /* record */[
          /* dbconn */"foo",
          /* transactionId */"2",
          /* data : Request */Block.__(0, [req])
        ];
}

function buildResponse(resp) {
  if (resp.tag) {
    return Types$Iconixfw.fresolve(resp[0]);
  } else {
    return Types$Iconixfw.freject("Invalid output from login Auth process");
  }
}

var deps = /* record */[
  /* buildReq */buildReq,
  /* worker */worker,
  /* buildResponse */buildResponse,
  /* runFsm */runFsm
];

function get(param) {
  return deps;
}

function buildResponse$1(resp) {
  if (resp.tag) {
    return Types$Iconixfw.fresolve(resp[0]);
  } else {
    return Types$Iconixfw.freject("Invalid output from login Auth process");
  }
}

function buildReq$1(req) {
  return /* record */[
          /* dbconn */"foo",
          /* transactionId */"2",
          /* data : Request */Block.__(0, [req])
        ];
}

function worker$1(ctx) {
  var match = ctx[/* data */2];
  if (match.tag) {
    return Types$Iconixfw.freject("invalid input to login worker");
  } else {
    var req = match[0];
    return Infix$Iconixfw.$less$$great(Db$Iconixfw.FakeDb[/* login */2](req[/* username */0], req[/* password */1]), (function (param) {
                  var ctx$1 = ctx;
                  var user = param;
                  return TransactionFsm$Iconixfw.updateWorkerData(ctx$1, /* LoginSession */Block.__(1, [/* record */[
                                  /* email */user[/* email */1],
                                  /* username */user[/* username */2],
                                  /* accessToken */user[/* accessToken */4]
                                ]]));
                }));
  }
}

var deps$1 = /* record */[
  /* buildReq */buildReq$1,
  /* worker */worker$1,
  /* buildResponse */buildResponse$1,
  /* runFsm */runFsm
];

function get$1(param) {
  return deps$1;
}

var FindWidgetDeps = [get];

var LoginDeps = [get$1];

exports.FindWidgetDeps = FindWidgetDeps;
exports.LoginDeps = LoginDeps;
/* Db-Iconixfw Not a pure module */
