// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Infix$Iconixfw = require("../framework/parser/Infix.bs.js");
var FsmGeneric$Iconixfw = require("../framework/Fsm/FsmGeneric.bs.js");
var TransactionFsm$Iconixfw = require("../framework/Fsm/TransactionFsm.bs.js");

function connect(data) {
  return Infix$Iconixfw.$less$$great(FsmGeneric$Iconixfw.Fsm[/* taskRunAndInject */6](TransactionFsm$Iconixfw.doNothing, /* Connected */0, TransactionFsm$Iconixfw.taplog("(Fake) connecting..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) connected", param);
              }));
}

function beginTransaction(data) {
  return Infix$Iconixfw.$less$$great(FsmGeneric$Iconixfw.Fsm[/* taskRunAndInject */6](TransactionFsm$Iconixfw.doNothing, /* Nothing */6, TransactionFsm$Iconixfw.taplog("(Fake) beginTransaction_ing..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) beginTransaction_ed", param);
              }));
}

function commit(data) {
  return Infix$Iconixfw.$less$$great(FsmGeneric$Iconixfw.Fsm[/* taskRunAndInject */6](TransactionFsm$Iconixfw.doNothing, /* CommitDone */4, TransactionFsm$Iconixfw.taplog("(Fake) commit_ing..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) commit_ed", param);
              }));
}

function rollback(data) {
  return Infix$Iconixfw.$less$$great(FsmGeneric$Iconixfw.Fsm[/* taskRunAndInject */6](TransactionFsm$Iconixfw.doNothing, /* RollbackDone */5, TransactionFsm$Iconixfw.taplog("(Fake) rollback_ing..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) rollback_ed", param);
              }));
}

function commitDone(data) {
  return Infix$Iconixfw.$less$$great(FsmGeneric$Iconixfw.Fsm[/* taskRunAndInject */6](TransactionFsm$Iconixfw.doNothing, /* Nothing */6, TransactionFsm$Iconixfw.taplog("(Fake) post commit..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) post commit done", param);
              }));
}

function rollbackDone(data) {
  return Infix$Iconixfw.$less$$great(FsmGeneric$Iconixfw.Fsm[/* taskRunAndInject */6](TransactionFsm$Iconixfw.doNothing, /* Nothing */6, TransactionFsm$Iconixfw.taplog("(Fake) post rollback..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) post rollback done", param);
              }));
}

function transactionDone(data) {
  return Infix$Iconixfw.$less$$great(TransactionFsm$Iconixfw.doNothing(TransactionFsm$Iconixfw.taplog("(Fake) transaction post cleanup..", data)), (function (param) {
                return TransactionFsm$Iconixfw.taplog("(Fake) transaction post cleanup done", param);
              }));
}

var FakeTransactionFsm = TransactionFsm$Iconixfw.MakeTransaction([
      connect,
      beginTransaction,
      commit,
      commitDone,
      rollback,
      rollbackDone,
      transactionDone
    ]);

exports.FakeTransactionFsm = FakeTransactionFsm;
/* FakeTransactionFsm Not a pure module */
