// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var MyProcess$Iconixfw = require("./MyProcess.bs.js");

function resolve(data) {
  console.log(data[/* token */0]);
  return /* () */0;
}

console.log("We are expecting output of 186. Actual result:");

MyProcess$Iconixfw.run(/* record */[/* token */30], (function (prim) {
        console.log(prim);
        return /* () */0;
      }), resolve);

exports.resolve = resolve;
/*  Not a pure module */
