// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Infix$Iconixfw = require("../parser/Infix.bs.js");
var Steps$Iconixfw = require("./Steps.bs.js");
var Types$Iconixfw = require("../../types/Types.bs.js");

function createProcess(input) {
  return Infix$Iconixfw.$great$great$eq(Infix$Iconixfw.$great$great$eq(Infix$Iconixfw.$great$great$eq(Types$Iconixfw.fresolve(input), Steps$Iconixfw.asyncIncr), Steps$Iconixfw.syncTriple), Steps$Iconixfw.asyncDouble);
}

function run(input, rej, resolve) {
  return Types$Iconixfw.ffork(rej, resolve, createProcess(input));
}

exports.createProcess = createProcess;
exports.run = run;
/* Infix-Iconixfw Not a pure module */
