// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function mapDefinition(f, eq) {
  var mapFlow = function (p) {
    if (typeof p === "number") {
      return /* Noop */0;
    } else {
      switch (p.tag | 0) {
        case 0 : 
            return /* Step */Block.__(0, [
                      p[0],
                      Curry._1(f, p[1])
                    ]);
        case 1 : 
            return /* CondStep */Block.__(1, [
                      p[0],
                      mapFlow(p[1]),
                      mapFlow(p[2])
                    ]);
        case 2 : 
            return /* Sequence */Block.__(2, [
                      mapFlow(p[0]),
                      mapFlow(p[1])
                    ]);
        case 3 : 
            return /* Parallel */Block.__(3, [List.map(mapFlow, p[0])]);
        
      }
    }
  };
  return /* Definition */[
          eq[0],
          mapFlow(eq[1])
        ];
}

exports.mapDefinition = mapDefinition;
/* No side effect */
