// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Types$Iconixfw = require("../../types/Types.bs.js");
var Engine$Iconixfw = require("./Engine.bs.js");

function evalPredicate(str, data) {
  console.log(/* tuple */[
        str,
        data
      ]);
  return true;
}

function mapper(k) {
  return (function (x) {
      console.log("No matching function, no-op: " + k);
      return Types$Iconixfw.fresolve(x);
    });
}

var preHook = Types$Iconixfw.fIdentity;

var tapStepBefore = Engine$Iconixfw.logPre;

var tapStepAfter = Engine$Iconixfw.logPost;

var postHook = Types$Iconixfw.fIdentity;

var fold = List.hd;

exports.preHook = preHook;
exports.tapStepBefore = tapStepBefore;
exports.tapStepAfter = tapStepAfter;
exports.postHook = postHook;
exports.fold = fold;
exports.evalPredicate = evalPredicate;
exports.mapper = mapper;
/* Types-Iconixfw Not a pure module */
