// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var BsFluture = require("bs-fluture/lib/js/src/BsFluture.js");

function $great$great$eq(a, f) {
  return BsFluture.chain(f, a);
}

function $less$$great(a, f) {
  return BsFluture.map(f, a);
}

exports.$great$great$eq = $great$great$eq;
exports.$less$$great = $less$$great;
/* BsFluture Not a pure module */
