// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var Types$Iconixfw = require("../../types/Types.bs.js");

var funcs_000 = /* tuple */[
  "incr",
  (function (param) {
      return Types$Iconixfw.fresolve(/* record */[/* token */param[/* token */0] + 1 | 0]);
    })
];

var funcs_001 = /* :: */[
  /* tuple */[
    "mult10",
    (function (param) {
        return Types$Iconixfw.fresolve(/* record */[/* token */Caml_int32.imul(param[/* token */0], 10)]);
      })
  ],
  /* :: */[
    /* tuple */[
      "double",
      (function (param) {
          var token = param[/* token */0];
          return Types$Iconixfw.fresolve(/* record */[/* token */token + token | 0]);
        })
    ],
    /* [] */0
  ]
];

var funcs = /* :: */[
  funcs_000,
  funcs_001
];

function mapper(k) {
  return List.assoc(k, funcs);
}

var Str2FuncMap = 0;

exports.Str2FuncMap = Str2FuncMap;
exports.funcs = funcs;
exports.mapper = mapper;
/* Types-Iconixfw Not a pure module */
