// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Infix$Iconixfw = require("../framework/parser/Infix.bs.js");
var Types$Iconixfw = require("../types/Types.bs.js");

function buildResponse(resp) {
  if (resp.tag) {
    return Types$Iconixfw.fresolve(resp[0]);
  } else {
    return Types$Iconixfw.freject("Invalid output from login Auth process");
  }
}

function getWidget(deps, req) {
  return Infix$Iconixfw.$great$great$eq(Curry._2(deps[/* runFsm */3], deps[/* worker */1], Curry._1(deps[/* buildReq */0], req)), deps[/* buildResponse */2]);
}

exports.buildResponse = buildResponse;
exports.getWidget = getWidget;
/* Infix-Iconixfw Not a pure module */
