// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");

var widgetStore = Belt_MapString.set(Belt_MapString.set(Belt_MapString.fromArray(/* array */[]), "id1", /* record */[
          /* id */"id1",
          /* name */"firstwidget"
        ]), "id2", /* record */[
      /* id */"id2",
      /* name */"secondwidget"
    ]);

var userStore = Belt_MapString.set(Belt_MapString.set(Belt_MapString.fromArray(/* array */[]), "user1", /* record */[
          /* id */"1",
          /* email */"user1@example.com",
          /* username */"user1",
          /* passHash */"1234",
          /* accessToken */"token1"
        ]), "user2", /* record */[
      /* id */"2",
      /* email */"user2@example.com",
      /* username */"user2",
      /* passHash */"1234",
      /* accessToken */"token2"
    ]);

exports.widgetStore = widgetStore;
exports.userStore = userStore;
/* widgetStore Not a pure module */
