// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Data$Iconixfw = require("./Data.bs.js");
var Belt_MapString = require("bs-platform/lib/js/belt_MapString.js");
var Types$Iconixfw = require("../../types/Types.bs.js");

var widgetStore = /* record */[/* contents */Data$Iconixfw.widgetStore];

var userStore = /* record */[/* contents */Data$Iconixfw.userStore];

function connect(param) {
  return Types$Iconixfw.fresolve(/* Fake */0);
}

function login(userName, passHash) {
  var maybeUser = Belt_MapString.get(userStore[0], userName);
  if (maybeUser !== undefined) {
    var user = maybeUser;
    if (user[/* passHash */3] === passHash) {
      return Types$Iconixfw.fresolve(user);
    } else {
      return Types$Iconixfw.freject("Invalid credentials");
    }
  } else {
    return Types$Iconixfw.freject("Invalid credentials");
  }
}

function findWidget(id) {
  var match_ = Belt_MapString.get(widgetStore[0], id);
  if (match_ !== undefined) {
    return Types$Iconixfw.fresolve(match_);
  } else {
    return Types$Iconixfw.freject("Not found");
  }
}

function addWidget(widget) {
  widgetStore[0] = Belt_MapString.set(widgetStore[0], widget[/* id */0], widget);
  return Types$Iconixfw.fresolve(widget);
}

var FakeDb = /* module */[
  /* connection : Fake */0,
  /* connect */connect,
  /* login */login,
  /* findWidget */findWidget,
  /* addWidget */addWidget
];

exports.widgetStore = widgetStore;
exports.userStore = userStore;
exports.FakeDb = FakeDb;
/* Data-Iconixfw Not a pure module */
