// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Types$Iconixfw = require("../../../types/Types.bs.js");
var Engine$Iconixfw = require("../Engine.bs.js");
var DomainDefaults$Iconixfw = require("../DomainDefaults.bs.js");

function testdataTypeToJs(param) {
  return {
          token: param[/* token */0]
        };
}

function testdataTypeFromJs(param) {
  return /* record */[/* token */param.token];
}

function mapMaybe(f, maybe) {
  return Belt_Option.map(maybe, f);
}

var Domain = /* module */[
  /* preHook */DomainDefaults$Iconixfw.preHook,
  /* tapStepBefore */DomainDefaults$Iconixfw.tapStepBefore,
  /* tapStepAfter */DomainDefaults$Iconixfw.tapStepAfter,
  /* postHook */DomainDefaults$Iconixfw.postHook,
  /* fold */DomainDefaults$Iconixfw.fold,
  /* evalPredicate */DomainDefaults$Iconixfw.evalPredicate,
  /* mapper */DomainDefaults$Iconixfw.mapper
];

var spec = "x = incr -> foo->  junk ->\n        mult100 -> double ->\n        morejunk ->\n        mult10 ->\n        incr -> blah ->\n        incr";

var MyProcess = Engine$Iconixfw.Make([
      DomainDefaults$Iconixfw.preHook,
      DomainDefaults$Iconixfw.tapStepBefore,
      DomainDefaults$Iconixfw.tapStepAfter,
      DomainDefaults$Iconixfw.postHook,
      DomainDefaults$Iconixfw.evalPredicate,
      DomainDefaults$Iconixfw.mapper,
      DomainDefaults$Iconixfw.fold
    ]);

var input = /* record */[/* token */180];

Types$Iconixfw.ffork((function (prim) {
        console.log(prim);
        return /* () */0;
      }), (function (prim) {
        console.log(prim);
        return /* () */0;
      }), Curry._2(MyProcess[/* run */14], spec, input));

exports.testdataTypeToJs = testdataTypeToJs;
exports.testdataTypeFromJs = testdataTypeFromJs;
exports.mapMaybe = mapMaybe;
exports.Domain = Domain;
exports.spec = spec;
exports.MyProcess = MyProcess;
exports.input = input;
/* MyProcess Not a pure module */
