// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var def1 = /* Equation */[
  "sampleProcess1",
  /* Step */Block.__(0, ["a"])
];

var def2 = /* Equation */[
  "sampleProcess2",
  /* Sequence */Block.__(2, [
      "a",
      /* Step */Block.__(0, ["b"])
    ])
];

var def3 = /* Equation */[
  "sampleProcess3",
  /* Sequence */Block.__(2, [
      "a",
      /* Sequence */Block.__(2, [
          "b",
          /* Step */Block.__(0, ["c"])
        ])
    ])
];

var def4 = /* Equation */[
  "sampleProcess4",
  /* Sequence */Block.__(2, [
      "a",
      /* Parallel */Block.__(1, [
          "b",
          /* Step */Block.__(0, ["c"])
        ])
    ])
];

var def5 = /* Equation */[
  "sampleProcess5",
  /* Sequence */Block.__(2, [
      "a",
      /* Parallel */Block.__(1, [
          "b",
          /* Parallel */Block.__(1, [
              "c",
              /* Sequence */Block.__(2, [
                  "d",
                  /* Step */Block.__(0, ["e"])
                ])
            ])
        ])
    ])
];

function dumpPhrase(ph) {
  switch (ph.tag | 0) {
    case 0 : 
        return ph[0];
    case 1 : 
        return ph[0] + (" || " + dumpPhrase(ph[1]));
    case 2 : 
        return ph[0] + (" -> " + dumpPhrase(ph[1]));
    
  }
}

function dump(eq) {
  return eq[0] + (" = " + dumpPhrase(eq[1]));
}

console.log(dump(def1));

console.log(dump(def2));

console.log(dump(def3));

console.log(dump(def4));

console.log(dump(def5));

exports.def1 = def1;
exports.def2 = def2;
exports.def3 = def3;
exports.def4 = def4;
exports.def5 = def5;
exports.dumpPhrase = dumpPhrase;
exports.dump = dump;
/*  Not a pure module */
