// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Parser$Iconixfw = require("../Parser.bs.js");
var AstDump$Iconixfw = require("../AstDump.bs.js");

function print(x) {
  console.log(AstDump$Iconixfw.dump(x));
  return /* () */0;
}

function test(param) {
  var maybed = Parser$Iconixfw.FlowParser[/* parseDefinition */13]("myproc = a?al:ar -> b?bl:br || c ? cl : cr || c2 -> d?dl:dr");
  console.log(maybed !== undefined ? AstDump$Iconixfw.dumpFlow(maybed) : "Invalid process definition");
  return /* () */0;
}

test(/* () */0);

function dotest2(param) {
  console.log(List.map(AstDump$Iconixfw.dumpFlow, Parser$Iconixfw.FlowParser[/* parsePara */14]("\n  # Comment\n  p = a->b -> #comment\n  c || pq -> zx; #comment\n  q = abc -> def -> f21# comment")));
  return /* () */0;
}

dotest2(/* () */0);

exports.print = print;
exports.test = test;
exports.dotest2 = dotest2;
/*  Not a pure module */
