// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Types$Iconixfw = require("../types/Types.bs.js");
var LoginProcess$Iconixfw = require("../processlayer/auth/LoginProcess.bs.js");

function login(deps, username, password) {
  var req = /* record */[
    /* username */username,
    /* password */password
  ];
  return LoginProcess$Iconixfw.login(deps, req);
}

exports.login = login;
/* Types-Iconixfw Not a pure module */
