// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Types$Iconixfw = require("../types/Types.bs.js");
var GetWidgetProcess$Iconixfw = require("../processlayer/GetWidgetProcess.bs.js");

function showWidget(deps, request) {
  return GetWidgetProcess$Iconixfw.getWidget(deps, /* record */[/* id */request[/* payload */1]]);
}

function addWidget(request) {
  var match = request[/* payload */1];
  return Types$Iconixfw.fresolve(match[0]);
}

exports.showWidget = showWidget;
exports.addWidget = addWidget;
/* Types-Iconixfw Not a pure module */
