// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';


function dummyCheck(accessToken) {
  return accessToken === "token1";
}

function isValidToken(accessToken) {
  if (accessToken === "token1") {
    return true;
  } else {
    return accessToken === "token2";
  }
}

var isSuperAdmin = dummyCheck;

var isFwAdmin = dummyCheck;

var isLicenseAdmin = dummyCheck;

var isAppStoreAdmin = dummyCheck;

var isConfigAdmin = dummyCheck;

exports.dummyCheck = dummyCheck;
exports.isSuperAdmin = isSuperAdmin;
exports.isFwAdmin = isFwAdmin;
exports.isLicenseAdmin = isLicenseAdmin;
exports.isAppStoreAdmin = isAppStoreAdmin;
exports.isConfigAdmin = isConfigAdmin;
exports.isValidToken = isValidToken;
/* No side effect */
