// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Infix$Iconixfw = require("../../framework/parser/Infix.bs.js");

function login(deps, req) {
  return Infix$Iconixfw.$great$great$eq(Curry._2(deps[/* runFsm */3], deps[/* worker */1], Curry._1(deps[/* buildReq */0], req)), deps[/* buildResponse */2]);
}

exports.login = login;
/* Infix-Iconixfw Not a pure module */
